<?php
$labels['imap_apppasswd'] = "Anwendungsspezifische Kennwörter (beta)";

$labels['last_used'] = "Zuletzt benutzt";
$labels['never_used'] = "noch nie verwendet";
$labels['last_used_from'] = "von";
$labels['created'] = "Erstellt";
$labels['unnamed_app'] = "Unbenannte Anwendung";
$labels['delete'] = "Löschen";
$labels['delete_all'] = "Alle Löschen";
$labels['add'] = "Hinzufügen";
$labels['copied'] = "Kennwort in Zwischenablage kopiert";
$labels['copy_failed_check_perms'] = "Fehler beim kopieren des Kennwortes, bitte prüfe die Browserbrechtigungen";
$labels['edit'] = "Bearbeiten";
$labels['done'] = 'Fertig';
$labels['ok'] = 'OK';

$labels['no_passwords'] = 'Es wurden noch keine Anwendungsspezifischen Kennworte erstellt. Du kannst durch klicken des Hinzufügen Knopfes eines erstellen.';

$labels['apppw_deleted_success'] = 'Anwendungsspezifisches Kennwort erfolgreich gelöscht';
$labels['apppw_deleted_error'] = 'Fehler beim löschen des Anwendungsspezifischen Kennwortes, bitte versuche es später erneut';
$labels['apppw_add_error'] = 'Fehler beim hinzufügen eines Anwendungsspezifischen Kennwortes, bitte versuche es später erneut';
$labels['apppw_rename_error'] = 'Fehler beim umbennenen des Anwendungsspezifischen Kennwortes, bitte versuche es später erneut';

$labels['years_ago'] = "vor %s Jahr(en)";
$labels['months_ago'] = "vor %s Monat(en)";
$labels['days_ago'] = "vor %s Tag(en)";
$labels['hours_ago'] = "vor %s Stunde(n)";
$labels['minutes_ago'] = "vor %s Minute(n)";
$labels['just_now'] = "gerade Ebend";

$labels['page_allows_password_creation_for_clients'] = <<<EOT
Auf dieser Seite kannst du anwendungsspezifische Kennwörter für deine E-mail Anwendungen erstellen. Nach der Erstellung
wird dir dieses Kennwort einmal gezeigt werden so das du es in der Anwendung eingeben oder einfügen kannst. Du musst und
sollst dir dieses Kennwort nicht merken oder notieren. Wenn du weiteres Kennwort für eine weitere Anwendung benötigst,
kannst du einfach ein neues erstellen; und das beliebig oft.
EOT;

$labels['use_the_following_settings'] = "Nutze die folgenden Einstellungen für deine Anwendung";
$labels['server'] = "Server";
$labels['port'] = "Port";
$labels['protocol'] = "Verbindungssicherheit";
$labels['password_method'] = "Authentifizierungs Methode";

$labels['imap_setting'] = "Eingehende (IMAP) Einstellungen";
$labels['smtp_setting'] = "Ausgehenede (SMTP) Einstellungen";
