<?php
$labels['imap_apppasswd'] = "App Passwords";

$labels['last_used'] = "Last used";
$labels['never_used'] = "Never used";
$labels['last_used_from'] = "from";
$labels['created'] = "Created";
$labels['unnamed_app'] = "Unnamed App";
$labels['delete'] = "Delete";
$labels['delete_all'] = "Delete All";
$labels['add'] = "Add";
$labels['copied'] = "Password copied to clipboard";
$labels['copy_failed_check_perms'] = "Failed copying password, check browser permissions";
$labels['edit'] = "Edit";
$labels['done'] = 'Done';
$labels['ok'] = 'OK';

$labels['apppw_deleted_success'] = 'App Password successfully deleted';
$labels['apppw_deleted_error'] = 'Error deleting App Password, please try again later';
$labels['apppw_add_error'] = 'Error adding password, please try again later';
$labels['apppw_rename_error'] = 'Error renaming password, please try again later';

$labels['years_ago'] = "%s year(s) ago";
$labels['months_ago'] = "%s month(s) ago";
$labels['days_ago'] = "%s day(s) ago";
$labels['hours_ago'] = "%s hour(s) ago";
$labels['minutes_ago'] = "%s minute(s) ago";
$labels['just_now'] = "just now";

$labels['page_allows_password_creation_for_clients'] = <<<EOT
This page allows to create App Password for your Mail clients. After creating a password, it will shown to once for you
to type or copy it to the client. You are not supposed or required to remember or take note of the password. If you want
to add an additional client, just create a new password; you can create as many as you want.
EOT;

$labels['use_the_following_settings'] = "Use the following settings for you client";
$labels['server'] = "Server";
$labels['port'] = "Port";
$labels['protocol'] = "Connection Security";
$labels['password_method'] = "Authentication Method";

$labels['imap_setting'] = "Incoming (IMAP) Setting";
$labels['smtp_setting'] = "Outgoing (SMTP) Setting";
