<?php
$labels['imap_apppasswd'] = "Mots de passe spécifiques à l'application (beta)";

$labels['last_used'] = "Dernière utilisation";
$labels['never_used'] = "Jamais utilisé";
$labels['last_used_from'] = "de";
$labels['created'] = "créé";
$labels['unnamed_app'] = "Application sans nom";
$labels['unknown_location'] = "Lieu inconnu";
$labels['delete'] = "Supprimer";
$labels['delete_all'] = "Supprimer tout";
$labels['confirm_delete_single'] = "Etes-vous sûr de vouloir supprimer le mot de passe \"%password%\"? Cette action ne peut pas être annulée.";
$labels['confirm_delete_all'] = "Êtes-vous sûr de vouloir supprimer TOUS les mots de passe de votre application? Cette action ne peut pas être annulée.";
$labels['add'] = "Ajouter";
$labels['copied'] = "Mot de passe copié dans le presse-papiers";
$labels['copy_failed_check_perms'] = "Échec de la copie du mot de passe, vérifier les permissions du navigateur";
$labels['edit'] = "Editer";
$labels['done'] = "Finition";
$labels['ok'] = "D'accord";

$labels['no_passwords'] = "Aucun mot de passe d'application n'a encore été créé. Vous pouvez en créer un ci-dessous en cliquant sur le bouton Ajouter.";

$labels['apppw_deleted_success'] = "Mot de passe de l'application supprimé avec succès";
$labels['apppw_deleted_error'] = "Erreur de suppression du mot de passe de l'application, veuillez réessayer plus tard";
$labels['apppw_add_error'] = "Erreur lors de l'ajout du mot de passe, veuillez réessayer plus tard";
$labels['apppw_rename_error'] = "Erreur de renommage du mot de passe, veuillez réessayer plus tard";

$labels['years_ago'] = "il y a %s an(s)";
$labels['months_ago'] = "il y a %s mois";
$labels['days_ago'] = "il y a %s jour(s)";
$labels['hours_ago'] = "il y a %s heure";
$labels['minutes_ago'] = "il y a %s minute(s)";
$labels['just_now'] = "à l'instant";

$labels['page_allows_password_creation_for_clients'] = <<<EOT
Cette page permet de créer un mot de passe pour vos clients de messagerie. Après avoir créé un mot de passe, celui-ci 
s'affichera une fois pour que vous puissiez le taper ou le copier dans l'application. Vous n'êtes ni censé ni tenu de 
vous souvenir du mot de passe ou d'en prendre note. Si vous souhaitez ajouter un client supplémentaire, il vous suffit 
de créer un nouveau mot de passe ; vous pouvez en créer autant que vous le souhaitez.
EOT;

$labels['use_the_following_settings'] = "Utilisez les paramètres suivants pour votre application";
$labels['server'] = "Serveur";
$labels['port'] = "Port";
$labels['protocol'] = "Sécurité des connexions";
$labels['password_method'] = "Méthode d'authentification";

$labels['imap_setting'] = "Paramètres des messages entrants (IMAP)";
$labels['smtp_setting'] = "Paramètres des messages sortants (SMTP)";
