<?php
/*
 * Copyright (c) 2026. Bennet Becker <dev@bennet.cc>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/imap_apppasswd">bennet0496/imap_apppasswd</a>';

$labels['imap_apppasswd'] = 'Uygulama Şifreleri';

$labels['last_used'] = 'Son kullanıldı';
$labels['never_used'] = 'Hiç kullanılmadı';
$labels['last_used_from'] = 'şu tarihten itibaren';
$labels['created'] = 'Oluşturuldu';
$labels['unnamed_app'] = 'İsimsiz Uygulama';
$labels['unknown_location'] = 'Bilinmeyen konum';
$labels['delete'] = 'Sil';
$labels['delete_all'] = 'Tümünü Sil';
$labels['confirm_delete_single'] = 'Şifreyi "$password" silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.';
$labels['confirm_delete_all'] = 'Tüm uygulama şifrelerinizi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.';
$labels['add'] = 'Ekle';
$labels['copied'] = 'Şifre panoya kopyalandı';
$labels['copy_failed_check_perms'] = 'Şifre kopyalanamadı, tarayıcı izinlerini kontrol edin';
$labels['edit'] = 'Düzenle';
$labels['done'] = 'Tamam';
$labels['ok'] = 'Tamam';

$labels['no_passwords'] = 'Henüz uygulama şifresi oluşturulmamıştır. Aşağıdaki Ekle düğmesine tıklayarak bir tane oluşturabilirsiniz.';

$labels['apppw_deleted_success'] = 'Uygulama şifresi başarıyla silindi';
$labels['apppw_deleted_error'] = 'Uygulama şifresi silinirken hata oluştu, lütfen daha sonra tekrar deneyin';
$labels['apppw_add_error'] = 'Şifre eklenirken hata oluştu, lütfen daha sonra tekrar deneyin';
$labels['apppw_rename_error'] = 'Şifre yeniden adlandırılırken hata oluştu, lütfen daha sonra tekrar deneyin';
$labels['apppw_rename_error_comment_is_password'] = 'Şifreyi kendi adınız olarak kullanamazsınız';
$labels['apppw_rename_error_too_long'] = 'Şifre adı çok uzun. Lütfen $max karakter veya daha az kullanın!';

$labels['years_ago'] = '$count yıl önce';
$labels['months_ago'] = '$count ay önce';
$labels['days_ago'] = '$count gün önce';
$labels['hours_ago'] = '$count saat önce';
$labels['minutes_ago'] = '$count dakika önce';
$labels['just_now'] = 'şimdi';

$labels['page_allows_password_creation_for_clients'] = <<<EOT
Bu sayfa e-posta istemcileriniz için Uygulama Şifreleri oluşturmanıza olanak tanır. Şifre oluşturduktan sonra, 
e-posta uygulamanıza girin veya kopyalayın. Şifre sadece bir kez gösterilecektir. Ancak şifreyi hatırlamak veya not almak 
gerekli değildir. Ek bir istemci eklemek istiyorsanız, yeni bir şifre oluşturun; istediğiniz kadar şifre oluşturabilirsiniz.
EOT;

$labels['use_the_following_settings'] = 'İstemciniz için aşağıdaki ayarları kullanın';
$labels['server'] = 'Sunucu';
$labels['port'] = 'Port';
$labels['protocol'] = 'Bağlantı Güvenliği';
$labels['password_method'] = 'Kimlik Doğrulama Yöntemi';

$labels['imap_setting'] = 'Gelen (IMAP) Ayarları';
$labels['smtp_setting'] = 'Giden (SMTP) Ayarları';

$labels['show_full_history'] = 'Erişim geçmişi göster';
$labels['timestamp'] = 'Zaman damgası';
$labels['service'] = 'Hizmet';
$labels['src_ip'] = 'Erişim IP';
$labels['src_rdns'] = 'Erişim Host Adı';
$labels['src_loc'] = 'Erişim Konumu';
$labels['src_isp'] = 'Erişim Hizmet Sağlayıcısı';
$labels['history_for'] = '$password için erişim geçmişi';
$labels['no_history'] = 'Geçmiş yok';
$labels['history_from_to_of'] = '$from ile $to arasında toplam $count kayıtlı giriş';

$labels['account_excluded'] = 'Hesabınız uygulama şifreleri kullanmaktan hariç tutulmuştur veya muaf tutulmuştur';